"""Hardware domain helpers."""

from .channel import (
    ChannelConfig,
    HardwareChannel,
    PluginChannelRule,
    channel_from_fields,
    channel_from_record,
    extract_board_channel_fields,
    get_channel_config,
    get_channel_config_for_record,
    get_fixed_baseline,
    get_gain_adc_per_pe,
    get_plugin_run_config,
    get_polarity,
    group_indices_by_hardware_channel,
    iter_hardware_channel_groups,
    iter_hardware_channel_indices,
    make_channel,
    normalize_channel_config_entry,
    require_board_channel_fields,
    resolve_channel_configs,
    resolve_channel_value_map,
    resolve_effective_channel_config,
    resolve_effective_channel_option,
    resolve_plugin_channel_overrides,
    unique_hardware_channels,
)

__all__ = [
    "ChannelConfig",
    "HardwareChannel",
    "PluginChannelRule",
    "channel_from_fields",
    "channel_from_record",
    "extract_board_channel_fields",
    "get_channel_config",
    "get_channel_config_for_record",
    "get_fixed_baseline",
    "get_gain_adc_per_pe",
    "get_polarity",
    "get_plugin_run_config",
    "group_indices_by_hardware_channel",
    "iter_hardware_channel_groups",
    "iter_hardware_channel_indices",
    "make_channel",
    "normalize_channel_config_entry",
    "require_board_channel_fields",
    "resolve_channel_configs",
    "resolve_effective_channel_config",
    "resolve_effective_channel_option",
    "resolve_plugin_channel_overrides",
    "resolve_channel_value_map",
    "unique_hardware_channels",
]
