"""Testing helpers for plugin development."""

from .fixtures import make_fake_st_waveforms, make_tiny_context
from .plugins import (
    FAKE_CURRENT_PIPELINE_PLUGINS,
    FAKE_PIPELINE_DTYPE,
    FakeHitMergedComponentsPlugin,
    FakeHitMergedFeaturesPlugin,
    FakeHitMergedPlugin,
    FakeHitPlugin,
    FakeHitThresholdPlugin,
    FakePeakClassificationPlugin,
    FakePeakletChannelsPlugin,
    FakePeakletComponentsPlugin,
    FakePeakletFeaturesPlugin,
    FakePeakletsPlugin,
    FakePeakletWaveformPoolPlugin,
    FakePeakletWaveformsPlugin,
    FakePeaksPlugin,
    FakeRecordsPlugin,
    FakeS1S2PairCandidatesPlugin,
    FakeS1S2PairsPlugin,
    FakeWavePoolPlugin,
    register_fake_current_pipeline,
)

__all__ = [
    "FAKE_CURRENT_PIPELINE_PLUGINS",
    "FAKE_PIPELINE_DTYPE",
    "FakeHitMergedComponentsPlugin",
    "FakeHitMergedFeaturesPlugin",
    "FakeHitMergedPlugin",
    "FakeHitPlugin",
    "FakeHitThresholdPlugin",
    "FakePeakClassificationPlugin",
    "FakePeakletChannelsPlugin",
    "FakePeakletComponentsPlugin",
    "FakePeakletFeaturesPlugin",
    "FakePeakletWaveformPoolPlugin",
    "FakePeakletWaveformsPlugin",
    "FakePeakletsPlugin",
    "FakePeaksPlugin",
    "FakeRecordsPlugin",
    "FakeS1S2PairCandidatesPlugin",
    "FakeS1S2PairsPlugin",
    "FakeWavePoolPlugin",
    "make_fake_st_waveforms",
    "make_tiny_context",
    "register_fake_current_pipeline",
]
