"""peaklet_waveform_pool bundle - provides 'peaklet_waveform_pool'。"""

from typing import Any
import warnings

import numpy as np

from waveform_analysis.core.plugins.builtin.peaklet_waveforms import (
    PeakletWaveformPlugin,
)
from waveform_analysis.core.plugins.builtin.peaklets._compute import (
    _get_context_memory,
    _store_context_memory,
)
from waveform_analysis.core.plugins.core.base import Plugin


class PeakletWaveformPoolPlugin(Plugin):
    """Return the pool produced alongside the canonical peaklet waveform index."""

    provides = "peaklet_waveform_pool"
    lineage_virtual = True
    depends_on = ["peaklet_waveforms"]
    description = (
        "Return the flattened float32 signal pool paired with peaklet_waveforms. "
        "Configure waveform construction on peaklet_waveforms."
    )
    version = "2.0.0"
    output_dtype = np.dtype("f4")
    save_when = "always"
    agent_doc = {
        "behavior_notes": [
            "Waveform construction options are owned by `peaklet_waveforms`; `peaklet_waveform_pool` has no independent configuration.",
            "Custom `peaklet_waveforms` providers must implement `build_pair(context, run_id)` so a missing pool can be rebuilt after a waveform cache hit.",
        ],
        "failure_modes": [
            "A custom `peaklet_waveforms` provider does not implement `build_pair(context, run_id)`.",
            "Legacy configuration remains under `peaklet_waveform_pool.*` instead of the canonical `peaklet_waveforms.*` namespace.",
        ],
        "agent_change_notes": [
            "v2.0.0: `peaklet_waveform_pool` now depends on `peaklet_waveforms`, so waveform version, config, dtype, and upstream lineage invalidate the paired pool cache.",
            "v2.0.0: Move all former `peaklet_waveform_pool.*` settings to `peaklet_waveforms.*`; the old namespace is ignored with a migration warning.",
            "Keep `peaklet_waveforms` index offsets and `peaklet_waveform_pool` values generated by the same `build_pair` implementation.",
        ],
    }
    doc_usage_example = """
    from waveform_analysis.core.context import Context
    from waveform_analysis.core.plugins.plugin_sets import (
        plugins_hit,
        plugins_io,
        plugins_waveform,
    )

    ctx = Context(config={"data_root": "DAQ"})
    ctx.register(*plugins_io(), *plugins_waveform(), *plugins_hit())

    # Construction options belong to the canonical waveform producer.
    ctx.set_config(
        {"use_filtered": False, "clip_negative_signal": False},
        plugin_name="peaklet_waveforms",
    )
    pool = ctx.get_data("run_001", "peaklet_waveform_pool")
    """

    options = {}
    _LEGACY_CONFIG_KEYS = tuple(PeakletWaveformPlugin.options)

    def _warn_legacy_config(self, context: Any) -> None:
        config = getattr(context, "config", {})
        config = config if isinstance(config, dict) else {}
        nested = config.get(self.provides, {})
        dotted_prefix = f"{self.provides}."
        has_legacy_config = isinstance(nested, dict) and any(
            name in nested for name in self._LEGACY_CONFIG_KEYS
        )
        has_legacy_config = has_legacy_config or any(
            isinstance(key, str) and key.startswith(dotted_prefix) for key in config
        )
        if has_legacy_config:
            warnings.warn(
                "Configuration under 'peaklet_waveform_pool' is ignored; configure "
                "the canonical 'peaklet_waveforms' plugin instead.",
                FutureWarning,
                stacklevel=2,
            )

    def compute(self, context: Any, run_id: str, **_kwargs) -> np.ndarray:
        self._warn_legacy_config(context)
        cached_pool = _get_context_memory(context, run_id, "peaklet_waveform_pool")
        if isinstance(cached_pool, np.ndarray):
            return np.asarray(cached_pool, dtype=np.float32)

        plugins = getattr(context, "_plugins", {})
        waveform_plugin = plugins.get("peaklet_waveforms")
        if waveform_plugin is None:
            waveform_plugin = PeakletWaveformPlugin()
        if not hasattr(waveform_plugin, "build_pair"):
            raise TypeError(
                "peaklet_waveform_pool requires the registered peaklet_waveforms provider "
                "to implement build_pair(context, run_id)"
            )

        waveforms, pool = waveform_plugin.build_pair(context, run_id)
        _store_context_memory(context, run_id, "peaklet_waveforms", waveforms)
        _store_context_memory(context, run_id, "peaklet_waveform_pool", pool)
        return pool


__all__ = ["PeakletWaveformPoolPlugin"]
