"""Public, lazy plugin facade.

This package is a physical facade rather than an alias for
``waveform_analysis.core.plugins``.  Importing it publishes the public map and
legacy module aliases only; plugin bundles and their scientific dependencies
are loaded when an individual export is first requested.
"""

from waveform_analysis._lazy_exports import (
    LazyExport as _LazyExport,
)
from waveform_analysis._lazy_exports import (
    lazy_dir as _lazy_dir,
)
from waveform_analysis._lazy_exports import (
    resolve_lazy_attribute as _resolve_lazy_attribute,
)
from waveform_analysis._module_aliases import (
    register_module_aliases as _register_module_aliases,
)

_CORE_PLUGINS = "waveform_analysis.core.plugins"
_BUILTIN = f"{_CORE_PLUGINS}.builtin"

# Keep this map explicit: it is the facade's import contract and must not be
# generated by scanning manifests or importing plugin bundles at runtime.
_LAZY_EXPORTS: dict[str, _LazyExport] = {
    # Plugin authoring API.
    "Plugin": (f"{_CORE_PLUGINS}.core.base", "Plugin"),
    "Option": (f"{_CORE_PLUGINS}.core.base", "Option"),
    "option": (f"{_CORE_PLUGINS}.core.base", "option"),
    "takes_config": (f"{_CORE_PLUGINS}.core.base", "takes_config"),
    # Plugin specification API.
    "PluginSpec": (f"{_CORE_PLUGINS}.core.spec", "PluginSpec"),
    "OutputSchema": (f"{_CORE_PLUGINS}.core.spec", "OutputSchema"),
    "FieldSpec": (f"{_CORE_PLUGINS}.core.spec", "FieldSpec"),
    "InputRequirement": (f"{_CORE_PLUGINS}.core.spec", "InputRequirement"),
    "Capabilities": (f"{_CORE_PLUGINS}.core.spec", "Capabilities"),
    "ConfigField": (f"{_CORE_PLUGINS}.core.spec", "ConfigField"),
    # Streaming and batch authoring API.
    "StreamingPlugin": (f"{_CORE_PLUGINS}.core.streaming", "StreamingPlugin"),
    "StreamingContext": (f"{_CORE_PLUGINS}.core.streaming", "StreamingContext"),
    "BatchProcessingPlugin": (
        f"{_CORE_PLUGINS}.core.batch_processing",
        "BatchProcessingPlugin",
    ),
    # Manifest-declared builtin plugin classes.  Each target is the canonical
    # leaf module so the object's identity and __module__ remain unchanged.
    "BasicFeaturesPlugin": (f"{_BUILTIN}.basic_features.plugin", "BasicFeaturesPlugin"),
    "CacheAnalysisPlugin": (f"{_BUILTIN}.cache_analysis.plugin", "CacheAnalysisPlugin"),
    "DataFramePlugin": (f"{_BUILTIN}.df.plugin", "DataFramePlugin"),
    "GroupedEventsPlugin": (f"{_BUILTIN}.df_events.plugin", "GroupedEventsPlugin"),
    "PairedEventsPlugin": (f"{_BUILTIN}.df_paired.plugin", "PairedEventsPlugin"),
    "EnergyReconstructionPlugin": (
        f"{_BUILTIN}.energy_reconstruction.plugin",
        "EnergyReconstructionPlugin",
    ),
    "EventPlugin": (f"{_BUILTIN}.events.plugin", "EventPlugin"),
    "FilteredWaveformsPlugin": (
        f"{_BUILTIN}.filtered_waveforms.plugin",
        "FilteredWaveformsPlugin",
    ),
    "HitFinderPlugin": (f"{_BUILTIN}.hit.plugin", "HitFinderPlugin"),
    "HitGroupedPlugin": (f"{_BUILTIN}.hit_grouped.plugin", "HitGroupedPlugin"),
    "HitMergeClustersPlugin": (
        f"{_BUILTIN}.hit_merge_clusters.plugin",
        "HitMergeClustersPlugin",
    ),
    "HitMergePlugin": (f"{_BUILTIN}.hit_merged.plugin", "HitMergePlugin"),
    "HitMergedComponentsPlugin": (
        f"{_BUILTIN}.hit_merged_components.plugin",
        "HitMergedComponentsPlugin",
    ),
    "HitMergedFeaturesPlugin": (
        f"{_BUILTIN}.hit_merged_features.plugin",
        "HitMergedFeaturesPlugin",
    ),
    "ThresholdHitPlugin": (f"{_BUILTIN}.hit_threshold.plugin", "ThresholdHitPlugin"),
    "PeakClassificationPlugin": (
        f"{_BUILTIN}.peak_classification.plugin",
        "PeakClassificationPlugin",
    ),
    "PeakletChannelsPlugin": (
        f"{_BUILTIN}.peaklet_channels.plugin",
        "PeakletChannelsPlugin",
    ),
    "PeakletComponentsPlugin": (
        f"{_BUILTIN}.peaklet_components.plugin",
        "PeakletComponentsPlugin",
    ),
    "PeakletFeaturesPlugin": (
        f"{_BUILTIN}.peaklet_features.plugin",
        "PeakletFeaturesPlugin",
    ),
    "PeakletWaveformPoolPlugin": (
        f"{_BUILTIN}.peaklet_waveform_pool.plugin",
        "PeakletWaveformPoolPlugin",
    ),
    "PeakletWaveformPlugin": (
        f"{_BUILTIN}.peaklet_waveforms.plugin",
        "PeakletWaveformPlugin",
    ),
    "PeakletPlugin": (f"{_BUILTIN}.peaklets.plugin", "PeakletPlugin"),
    "PeaksPlugin": (f"{_BUILTIN}.peaks.plugin", "PeaksPlugin"),
    "PositionReconstructionPlugin": (
        f"{_BUILTIN}.position_reconstruction.plugin",
        "PositionReconstructionPlugin",
    ),
    "RawFileNamesPlugin": (f"{_BUILTIN}.raw_files.plugin", "RawFileNamesPlugin"),
    "RecordsPlugin": (f"{_BUILTIN}.records.plugin", "RecordsPlugin"),
    "RecordsAsymmetryMaskPlugin": (
        f"{_BUILTIN}.records_asymmetry_mask.plugin",
        "RecordsAsymmetryMaskPlugin",
    ),
    "RecordsDetectorMaskPlugin": (
        f"{_BUILTIN}.records_detector_mask.plugin",
        "RecordsDetectorMaskPlugin",
    ),
    "RecordsVetoMaskPlugin": (
        f"{_BUILTIN}.records_veto_mask.plugin",
        "RecordsVetoMaskPlugin",
    ),
    "S1S2PairCandidatesPlugin": (
        f"{_BUILTIN}.s1_s2_pair_candidates.plugin",
        "S1S2PairCandidatesPlugin",
    ),
    "S1S2PairSelectionPlugin": (
        f"{_BUILTIN}.s1_s2_pairs.plugin",
        "S1S2PairSelectionPlugin",
    ),
    "SignalPeaksStreamPlugin": (
        f"{_BUILTIN}.signal_peaks_stream.plugin",
        "SignalPeaksStreamPlugin",
    ),
    "WaveformsPlugin": (f"{_BUILTIN}.st_waveforms.plugin", "WaveformsPlugin"),
    "WavePoolPlugin": (f"{_BUILTIN}.wave_pool.plugin", "WavePoolPlugin"),
    "WavePoolFilteredPlugin": (
        f"{_BUILTIN}.wave_pool_filtered.plugin",
        "WavePoolFilteredPlugin",
    ),
    "WaveformWidthPlugin": (
        f"{_BUILTIN}.waveform_width.plugin",
        "WaveformWidthPlugin",
    ),
    "WaveformWidthIntegralPlugin": (
        f"{_BUILTIN}.waveform_width_integral.plugin",
        "WaveformWidthIntegralPlugin",
    ),
    # Execution profiles.
    "cpu_default": (f"{_CORE_PLUGINS}.profiles", "cpu_default"),
    "streaming_default": (f"{_CORE_PLUGINS}.profiles", "streaming_default"),
    "jax_accel": (f"{_CORE_PLUGINS}.profiles", "jax_accel"),
    "get_profile": (f"{_CORE_PLUGINS}.profiles", "get_profile"),
    "PROFILES": (f"{_CORE_PLUGINS}.profiles", "PROFILES"),
    # Plugin-set factories and registry.
    "plugins_io": (f"{_CORE_PLUGINS}.plugin_sets", "plugins_io"),
    "plugins_waveform": (f"{_CORE_PLUGINS}.plugin_sets", "plugins_waveform"),
    "plugins_hit": (f"{_CORE_PLUGINS}.plugin_sets", "plugins_hit"),
    "plugins_peaks": (f"{_CORE_PLUGINS}.plugin_sets", "plugins_peaks"),
    "plugins_basic_features": (
        f"{_CORE_PLUGINS}.plugin_sets",
        "plugins_basic_features",
    ),
    "plugins_tabular": (f"{_CORE_PLUGINS}.plugin_sets", "plugins_tabular"),
    "plugins_events": (f"{_CORE_PLUGINS}.plugin_sets", "plugins_events"),
    "get_plugin_set": (f"{_CORE_PLUGINS}.plugin_sets", "get_plugin_set"),
    "PLUGIN_SETS": (f"{_CORE_PLUGINS}.plugin_sets", "PLUGIN_SETS"),
    # Module-level compatibility entries.  The alias finder keeps imports of
    # waveform_analysis.plugins.{profiles,sets} identical to their core paths.
    "profiles": (f"{_CORE_PLUGINS}.profiles", None),
    "sets": (f"{_CORE_PLUGINS}.plugin_sets", None),
}

__all__ = list(_LAZY_EXPORTS)

_register_module_aliases(
    {
        f"{__name__}.profiles": f"{_CORE_PLUGINS}.profiles",
        f"{__name__}.sets": f"{_CORE_PLUGINS}.plugin_sets",
    }
)


def __getattr__(name: str) -> object:
    return _resolve_lazy_attribute(name, _LAZY_EXPORTS, globals())


def __dir__() -> list[str]:
    return _lazy_dir(globals(), _LAZY_EXPORTS, __all__)
